### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by chanokin** [hbp-unibi/cypress#4] opened 2018-12-03 11:55 UTC
Hi

I tried installing the project and it marks an error while copying config.h. I believe the following line 
https://github.com/hbp-unibi/cypress/blob/26cdfd2f23d32f04ff4fa73aead203a8b0f44acd/CMakeLists.txt#L178
requires a change to 

`FILES ${CMAKE_BINARY_DIR}/include/cypress/config.h`

Is this the right thing to do?

**Comment by costrau** [comment] 2018-12-03 16:18
Hi,

thank you for your feedback. You are probably right, I put that on my TODO list. However, installing is the "old-faishoned" way to use the library. If you use cmake with your project, I would recommend to use https://github.com/hbp-unibi/SNABSuite/blob/master/cmake/cypress_external.cmake
It is less complicated and you do not need to keep track of any updates, the library will be updated at compile time...
I am sorry that the documentation isn't updated yet... If you have more feedback, I'd be very happy to help.

**Comment by costrau** [comment] 2019-01-16 16:01
Hey,

Sorry for the late reply... I cannot reproduce your problem on my system. Is your setup working with your proposed change? It would also help if you could show me the actual error message...

If you are okay with using my proposed workflow, I set up a minimal example on how to set up a project with cypress using cmake ExternalProject. Have a look at [https://github.com/hbp-unibi/cypress_example](https://github.com/hbp-unibi/cypress_example)

**Comment by costrau** [comment] 2019-07-01 08:48
I have addressed installation issues in #5. Please refer to Readme for more detailed installation instructions, section `Using Cypress in your own project`.

**Closed as completed by costrau** 2019-07-01 08:48 UTC
